default_context:
  project_name: 'advarium2'
  project_slug: 'advarium2'
  domain_main: 'auto80.local'
  domain_staging: 'stag.auto80.local'
  docker_swarm_stack_name_main: 'auto80-local'
  docker_swarm_stack_name_staging: 'stag-auto80-local'
  secret_key: 'qwas123'
  first_superuser: 'admin@auto80.local'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.auto80.local", "https://stag.auto80.local", "https://auto80.local", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@auto80.local'
  postgres_password: 'qwas123'
  pgadmin_default_user: 'admin@auto80.local'
  pgadmin_default_user_password: 'qwas123'
  traefik_constraint_tag: 'auto80.local'
  traefik_constraint_tag_staging: 'stag.auto80.local'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:qwas123'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
